
apiVersion: v1
kind: Namespace
metadata:
  name: webscraper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webscraper-node-deployment
  namespace: webscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webscraper-node
  template:
    metadata:
      labels:
        app: webscraper-node
    spec:
      containers:
        - name: webscraper-node-container
          image: ghcr.io/embedez/webscrapper-node:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
